name: chat_supabase
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.1
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  http: ^1.2.2
  connectivity_plus: ^6.0.4
  timeago: ^3.7.0
  supabase_flutter: ^2.6.0
  app_links: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

